<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[6]=array(0,1,1,'5bel5L2c5a6k5Yqo5oCB');
$cfg_Cs[4]=array(0,1,1,'6aaW6aG1');
$cfg_Cs[7]=array(0,1,1,'5qih54mI5bGV56S6');
$cfg_Cs[8]=array(0,1,1,'5pyN5Yqh6aG555uu');
$cfg_Cs[9]=array(0,1,1,'5Lu35qC85YiX6KGo');
$cfg_Cs[10]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[11]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[12]=array(0,1,1,'5o+Q5Lqk6K6i5Y2V');
$cfg_Cs[13]=array(0,2,1,'5rWL6K+V');
?>